### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by dirtycomputer** [MrGiovanni/AbdomenAtlas#2]
Nice work. When will you release the dataset?

**Comment by MrGiovanni** [comment]
Hi Xinyuan,

Thank you for your interest in our dataset. We're aiming to release it by late September or early October, depending on the acceptance of our paper. Fingers crossed!

Kindly keep an eye out for upcoming announcements.

Best,

Zongwei

**Comment by michaelmyc** [comment]
@MrGiovanni Hi Zongwei, 

I see that you've updated that the paper has been accepted. Congratulations! I'm wondering if there's a timeline for releasing the dataset. 

Thank you!

**Comment by dirtycomputer** [comment]
Any update?

**Comment by MrGiovanni** [comment]
Hi all,

Thank you for your patience. I'm pleased to announce that we have released a preliminary version of AbdomenAtlas. You can access it here: https://www.dropbox.com/scl/fi/28l5vpxrn212r2ejk32xv/AbdomenAtlas.tar.gz?rlkey=vgqmao4tgv51hv5ew24xx4xpm&dl=0

You will have to download the original CT volumes from their websites because we do not have the permission to distribute these CT volumes. The websites can be found at https://github.com/ljwztc/CLIP-Driven-Universal-Model#dataset

This dataset comprises 5,195 CT volumes with detailed per-voxel annotations for eight organs. While our paper initially committed to releasing 3,140 CT volumes, the availability of CT volumes in the public domain has grown, prompting us to extend our dataset. We are committed to further enhancing the dataset, applying our active learning strategy to annotate even more CT volumes and expanding to include additional organ types. Kindly stay updated, and I'd be grateful if you could share our dataset with interested colleagues.

Warm regards,
Zongwei
